/**
 * Returns the HTML template for the dial-selector component's shadow DOM.
 */
export function getTemplate(): string {
  return `
    <div class="selector" part="panel" role="listbox" aria-label="Dial selector">
      <div class="label-column left" id="leftColumn" part="labels label-row">
        <!-- Left labels will be generated by JavaScript -->
      </div>

      <div class="knob-wrap" part="dial">
        <svg
          id="lineContainer"
          width="100%"
          height="100%"
          style="position: absolute; overflow: visible;"
          aria-hidden="true"
        >
          <!-- Lines will be generated by JavaScript -->
        </svg>
        <div class="knob" part="knob">
          <slot name="knob-content">
            <!-- Default indicator when no custom content provided -->
            <div class="indicator" part="indicator"></div>
          </slot>
          <div class="advance" id="advanceButton" role="button" aria-label="Switch to next option"></div>
        </div>
      </div>

      <div class="label-column right" id="rightColumn" part="labels label-row">
        <!-- Right labels will be generated by JavaScript -->
      </div>

      <div class="dial-layout-overlay" aria-hidden="true">
        <div class="dial-container">
          <div class="options-container left"></div>
          <div class="knob-container"></div>
          <div class="options-container right"></div>
        </div>
      </div>
    </div>
    <!-- Live region for announcing selection changes to screen readers -->
    <div id="liveRegion" aria-live="polite" aria-atomic="true" class="visually-hidden"></div>
  `;
}
